#version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: armazem
    restart: always

    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: postgre
      POSTGRES_DB: dockF

    ports:
      - "5432:5432" #portaPC:portaDocker

    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: